src/main/resources/mybatis/mappers/MemberMapper.xml, src/main/resources/static/error/4xx.html, src/main/resources/static/error/5xx.html, src/main/resources/templates/Home.html, src/main/resources/templates/board/List.html, src/main/resources/templates/include/HeaderNavFooter.html, src/main/resources/templates/member/MemberLoginForm.html, src/main/resources/templates/menu/ShowMenuForm.html
=> OB-19-resources

src/main/java/com/oneteam/dormease/HomeController.java, src/main/java/com/oneteam/dormease/user/student/StudentDto.java, src/main/resources/application.properties
=> OB-18-application.properties

build.gradle, src/main/java/com/oneteam/dormease/HomeController.java, src/main/java/com/oneteam/dormease/config/SpringSecurityConfig.java, src/main/java/com/oneteam/dormease/user/parents/ParentsController.java, src/main/java/com/oneteam/dormease/user/student/IStudentMapper.java, src/main/java/com/oneteam/dormease/user/student/StudentController.java, src/main/java/com/oneteam/dormease/user/student/StudentDto.java, src/main/java/com/oneteam/dormease/user/student/StudentService.java, src/main/resources/application.properties, src/main/resources/mybatis/mappers/MemberMapper.xml, src/main/resources/mybatis/mappers/studentMapper.xml, src/main/resources/static/js/student/createAccountForm.js, src/main/resources/templates/Home.html, src/main/resources/templates/user/student/createAccountForm.html, src/main/resources/templates/user/student/createAccountResult.html
=> OB-20-회원 가입 기능 draft.ver 완료

src/main/java/com/oneteam/dormease/user/student/IStudentMapper.java, src/main/java/com/oneteam/dormease/user/student/StudentController.java, src/main/java/com/oneteam/dormease/user/student/StudentDto.java, src/main/java/com/oneteam/dormease/user/student/StudentService.java, src/main/resources/mybatis/mappers/studentMapper.xml, src/main/resources/static/js/student/createAccountForm.js, src/main/resources/static/js/student/loginForm.js, src/main/resources/templates/Home.html, src/main/resources/templates/user/student/createAccountForm.html, src/main/resources/templates/user/student/loginForm.html, src/main/resources/templates/user/student/loginResult.html
로그인 폼 생성 완료 
로그인 성공 시 홈 화면 
실패 시 로그인 화면으로 redirect
=> OB-24 로그인 폼 생성 완료

src/main/java/com/oneteam/dormease/user/student/IStudentMapper.java, src/main/java/com/oneteam/dormease/user/student/StudentController.java, src/main/java/com/oneteam/dormease/user/student/StudentService.java, src/main/resources/mybatis/mappers/studentMapper.xml, src/main/resources/templates/Home.html, src/main/resources/templates/include/common_js.html, src/main/resources/templates/include/modifyAccountFormJs.html, src/main/resources/templates/include/use_console.html, src/main/resources/templates/user/student/modifyAccountForm.html
로그아웃 -> 성공 시 홈으로 redirect
회원 탈퇴 -> 비동기, 성공 시 홈으로 redirect
회원 수정 -> 핸드폰 번호, 이메일 수정 중, 미완성
=> OB-27-학생로그아웃,회원탈퇴,수정폼

src/main/resources/static/css/home.css, src/main/resources/templates/Home.html, src/main/resources/templates/include/headerNavFooter.html
OB-28-Main-page-DashBoard-UI-설계 (CSS작업도 일부 완성했습니다.)
=> OB-28-Main-page-DashBoard-UI-설계

src/main/java/com/oneteam/dormease/api/ApiController.java, src/main/java/com/oneteam/dormease/api/ApiDto.java, src/main/java/com/oneteam/dormease/api/ApiService.java, src/main/java/com/oneteam/dormease/board/BoardController.java, src/main/resources/mybatis/mappers/boardMapper.xml, src/main/resources/static/ckeditor/config.js, src/main/resources/static/js/board/writeContentConfirm.js, src/main/resources/templates/board/writeContentForm.html, src/main/resources/templates/user/student/createAccountForm.html
OB-31 -학생 회원가입 우편번호 다음API 추가(DB수정)
-ck 에디터 코드 일부 수정
=> OB-31-회원가입에-우편번호-API-추가(DB-수정)

src/main/java/com/oneteam/dormease/user/student/IStudentMapper.java, src/main/java/com/oneteam/dormease/user/student/StudentController.java, src/main/java/com/oneteam/dormease/user/student/StudentService.java, src/main/resources/mybatis/mappers/studentMapper.xml, src/main/resources/templates/Home.html, src/main/resources/templates/include/loginFormJs.html, src/main/resources/templates/include/student/leaveOutFormJs.html, src/main/resources/templates/user/loginForm.html, src/main/resources/templates/user/student/leaveOutForm.html, src/main/resources/templates/user/student/leaveOutList.html
=> OB-45-외박-신청-폼

src/main/resources/templates/include/student/leaveOutFormJs.html, src/main/resources/templates/user/student/leaveOutForm.html
외박 폼 
복귀 날짜 입력 삭제 및 복귀 날짜 무조건 다음날로 저장
=> OB-52-외박-폼-수정

src/main/java/com/oneteam/dormease/api/ApiController.java, src/main/java/com/oneteam/dormease/board/BoardController.java, src/main/java/com/oneteam/dormease/board/BoardService.java, src/main/java/com/oneteam/dormease/board/reply/ReplyController.java, src/main/java/com/oneteam/dormease/board/reply/ReplyService.java, src/main/java/com/oneteam/dormease/user/member/UserController.java, src/main/java/com/oneteam/dormease/user/member/UserService.java, src/main/java/com/oneteam/dormease/user/parents/ParentsController.java, src/main/java/com/oneteam/dormease/user/parents/ParentsService.java, src/main/java/com/oneteam/dormease/user/student/StudentController.java, src/main/java/com/oneteam/dormease/user/student/StudentService.java, src/main/java/com/oneteam/dormease/utils/UploadFileService.java, src/main/resources/templates/board/modifyContentForm.html
User.ver에서 기존에 @Autowired로 주입되어있던 객체를
생성자 주입방식으로 변경함
=> OB-58-User.ver-의존성-주입방식-변경

src/main/java/com/oneteam/dormease/board/BoardController.java, src/main/java/com/oneteam/dormease/board/BoardService.java, src/main/java/com/oneteam/dormease/board/IBoardMapper.java, src/main/java/com/oneteam/dormease/notice/INoticeMapper.java, src/main/java/com/oneteam/dormease/notice/NoticeController.java, src/main/java/com/oneteam/dormease/notice/NoticeService.java, src/main/java/com/oneteam/dormease/utils/pagination/Criteria.java, src/main/java/com/oneteam/dormease/utils/pagination/PageDefine.java, src/main/java/com/oneteam/dormease/utils/pagination/PageMakerDto.java, src/main/resources/mybatis/mappers/boardMapper.xml, src/main/resources/static/css/headerFooter.css, src/main/resources/static/css/user/loginForm.css, src/main/resources/templates/board/detailContentForm.html, src/main/resources/templates/board/freeBoardListForm.html, src/main/resources/templates/board/modifyContentForm.html, src/main/resources/templates/board/writeContentForm.html, src/main/resources/templates/include/headerNavFooter.html, src/main/resources/templates/include/listJs.html, src/main/resources/templates/user/loginForm.html
첨부파일을 포함한 게시글 수정 기능 추가 
(기존 첨부파일 있을 때, 없을 때 모두 동작)
(새로운 첨부파일 있을 때, 없을 때 모두 동작)
기본 로그인 폼 css 작업 완료
=> OB-62-첨부파일을-포함한-게시글-수정기능-추가-css작업-일부-추가

src/main/java/com/oneteam/dormease/user/member/IUserMapper.java, src/main/java/com/oneteam/dormease/user/member/sms/SmsService.java, src/main/java/com/oneteam/dormease/user/parents/ParentsDto.java, src/main/java/com/oneteam/dormease/user/student/IStudentMapper.java, src/main/java/com/oneteam/dormease/user/student/StudentController.java, src/main/java/com/oneteam/dormease/user/student/StudentDto.java, src/main/java/com/oneteam/dormease/user/student/StudentService.java, src/main/resources/mybatis/mappers/parentsMapper.xml, src/main/resources/mybatis/mappers/studentMapper.xml, src/main/resources/mybatis/mappers/userMapper.xml, src/main/resources/templates/include/member/loginFormJs.html, src/main/resources/templates/user/loginForm.html
아이디 - fail_count 5회 이상 로그인 실패 시 막기(새 비밀번호 발급 시 다시 로그인 가능)
=> OB-66-로그인-fail_count-적용

src/main/java/com/oneteam/dormease/config/WebMvcConfig.java, src/main/java/com/oneteam/dormease/product/IProductMapper.java, src/main/java/com/oneteam/dormease/product/MySchoolProductDto.java, src/main/java/com/oneteam/dormease/product/ProductController.java, src/main/java/com/oneteam/dormease/product/ProductOrderDto.java, src/main/java/com/oneteam/dormease/product/ProductService.java, src/main/resources/mybatis/mappers/productMapper.xml, src/main/resources/static/css/product/home.css, src/main/resources/static/css/product/list.css, src/main/resources/static/js/product/findProduct.js, src/main/resources/static/js/product/registProductForm.js, src/main/resources/templates/Home.html, src/main/resources/templates/include/product/allProduct_js.html, src/main/resources/templates/include/product/selectProduct_js.html, src/main/resources/templates/product/mySchoolProductForm.html
1. 학생이 속한 학교의 상품 조회 기능 추가 
2. 클릭한 상품에 대해 1회 장바구니 담기 기능
3. 장바구니에 있던 상품을 한번 더 클릭 할 경우, 
장바구니에 1회 추가 담기
4. 장바구니에 담긴 상품은 각각 최소 1개, 최대 10개까지 담기 가능
5. 상품의 수량은 수량 좌우의 up, down 버튼을 통해 조절 가능
6. 상품과 각 상품의 수량을 상품 추가와 수량 변동에 따라 
실시간으로 계산하여 
각 상품 별 수량, 상품 별 총 가격, 모든 상품의 최종 가격을 표시
7. 위의 데이터들을 폼 데이터로 서버에 전송하고, DB에 전달
8. 장바구니에 담긴 상품을 삭제 처리할 경우,
사용자에게 보여지는 리스트와 폼 데이터를 변경하고
모든 상품의 총 가격을 다시 계산하여 보여준다.
9. 상품 관련 DB는
주문자, 이미지, 상품명, 상품수량, 상품별가격, 
수량에 따른 상품의 총 가격, 모든 상품의 총 가격,
등록날짜, 수정날짜로 구성
10. 기존 테이블 5 뷰에서 7 뷰로 변경
11. 검색 기능 추가
12. 전체 보기 추가 (검색 기능에 keyword='' 을 전달)
=> OB-72-학생-매점-키오스크-형식의-기능-및-검색-기능-추가

src/main/resources/static/css/product/list.css, src/main/resources/templates/include/product/paymentHistory_js.html, src/main/resources/templates/product/paymentHistory.html
=> OB-82-사용자-매점-내역-CSS-중간작업

src/main/java/com/oneteam/dormease/config/WebMvcConfig.java, src/main/java/com/oneteam/dormease/product/ProductController.java, src/main/java/com/oneteam/dormease/user/parents/ProductInterceptor.java, src/main/java/com/oneteam/dormease/user/student/StudentDto.java, src/main/resources/mybatis/mappers/productMapper.xml, src/main/resources/templates/include/product/allProduct_js.html, src/main/resources/templates/product/mySchoolProductForm.html, src/main/resources/templates/product/paymentHistory.html
1. 매점 관련 기능 인터셉트 설정
1-1. js 호출 후, setTimes를 통해 일정 시간 후 리다이렉트하도록 변경
2. 우리 학교 상품 보기에 대해 컨트롤러에서 테스트 계정으로 설정해 놓은 부분 세션 값 참조로 수정
3. 학생이 참조하는 학생의 학교 상품에 대해 status값이 누락된 것을 확인 및 수정
4. 내역 및 상세 내역에 관련하여 테스트 계정으로 설정해 놓은 부분 세션 값 참조로 수정
5. 학교에서 등록한 상품이 없을 경우 분기 생성
6. 학생의 내역이 없을 경우를 분기 생성
7. 상품 등록 완료 시, 리다이렉트_내역페이지로 변경
=> OB-88-학생-멤버링과-매점-및-인터셉트-연동

src/main/java/com/oneteam/dormease/config/SwaggerConfig.java, src/main/java/com/oneteam/dormease/user/member/IUserMapper.java, src/main/java/com/oneteam/dormease/user/student/StudentController.java, src/main/resources/mybatis/mappers/studentMapper.xml, src/main/resources/mybatis/mappers/userMapper.xml, src/main/resources/templates/user/student/leavePassResult.html
=> OB-93-외박-신청-및-내역-학생

src/main/java/com/oneteam/dormease/user/student/StudentController.java, src/main/resources/templates/include/board/listJs.html
=> OB-94-자유게시판-페이지네이션-노출

src/main/java/com/oneteam/dormease/config/WebMvcConfig.java, src/main/java/com/oneteam/dormease/product/ParentsInterceptor.java, src/main/java/com/oneteam/dormease/user/parents/ParentsController.java, src/main/java/com/oneteam/dormease/user/student/StudentController.java, src/main/java/com/oneteam/dormease/user/student/StudentInterceptor.java
=> OB-97-학생-학부모-로그인-인터셉터

src/main/resources/static/js/parents/createAccountForm.js, src/main/resources/templates/include/member/duplicateCheck.html, src/main/resources/templates/include/parents/createAccountFormJs.html, src/main/resources/templates/include/student/createAccountFormJs.html, src/main/resources/templates/user/member/findIDForm.html, src/main/resources/templates/user/member/findPasswordForm.html, src/main/resources/templates/user/parents/createAccountForm.html, src/main/resources/templates/user/parents/modifyAccountForm.html, src/main/resources/templates/user/student/createAccountForm.html, src/main/resources/templates/user/student/modifyAccountForm.html
기존에 문제가 있던 필터키 관련하여 해결
HTML :  filterKey() ===> filterKey(this)
JavaScript =>
function filterKey(inputElement) {
console.log("filterKey(this) CALLED!!!");
let inputValue = inputElement.value;
if (inputValue) {
// 입력값에 숫자 이외의 문자가 있는지 확인
if (/\D/.test(inputValue)) {
// 오류 메시지 표시
alert("숫자만 입력할 수 있습니다.");
// 입력값에서 숫자 이외의 문자를 제거하고 다시 설정
let filterNum = inputValue.replace(/\D/g, '');
inputElement.value = filterNum; // 값을 다시 설정
}
}
}
=> OB-98-유저-페이지-숫자-필터키-문제-해결

src/main/resources/static/js/product/findProduct.js
css 수정 및 html 구조 변경으로 인한 찾기 비동기 작업 에러 해결
=> OB-101-상품-찾기-기능-디버그-해결
